language : java
script :
    - mvn validate
    - mvn compile
    - mvn package
jdk : oraclejdk8
notifications:
    slack: intech-sudparis:Z3xKQEmZT2a9BFBqouokQ6J7
    on_success: change
    on_failure: always
